openapi: 3.0.1
info:
  title: Jess Backend
  description: API For different actions for Jessica.
  version: "v1"
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /finances/alpaca/performance:
    get:
      operationId: getPerformance
      summary: Get overall account performance from all the investments
      responses:
        '200':
          description: Successfully retrieved the account performance
          content:
            text/plain:
              schema:
                type: string
                example: "Net Investment: $1000.00\nCurrent Portfolio Value: $1500.00\nPortfolio Performance: 50.00%"
        '500':
          description: Error occurred, possibly due to authentication issues
  /current/datetime:
    get:
      operationId: getCurrentDateTime
      summary: Get the current date and time
      responses:
        '200':
          description: Current date and time returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  datetime:
                    type: string
                    example: '2023-12-04T15:30:00Z'
                    description: The current date and time in ISO 8601 format
        '500':
          description: Internal server error
  /memories/:
    post:
      operationId: storeMemory
      summary: Store a new memory/fact about a user so you can retrive it later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memory:
                  type: string
                  description: The memory or fact to store about the user
      responses:
        '200':
          description: Memory stored successfully
        '400':
          description: Bad request
    get:
      operationId: queryMemory
      summary: Ask a question about a user and relevant memories/facts will be retrived
      parameters:
        - name: question
          in: query
          required: true
          schema:
            type: string
            description: Query/question to use to retrieve relevant memory/facts about user
        - name: count
          in: query
          required: false
          schema:
            type: number
            description: Amount of facts/memories to return (sorted by relevance), default is 5
      responses:
        '200':
          description: Successfully retrieved the relevant memory
          content:
            application/json:
              schema:
                type: object
                properties:
                  memories:
                    type: array
                    description: A list of relevant memories or facts in response to the question
                    items:
                      type: string
        '400':
          description: Bad request
        '500':
          description: You need to re-authenticate
