investing_forecast_prompt = """I want you to create a weekly overview of the financial market, focusing on short-term, high-risk/high-reward investments. Your report should be concise, approximately 1-2 pages, and include:
TLDR of Key Upcoming Events:
   **Action**: Research and summarize the main financial and economic events scheduled for the upcoming week. Google searches for in-depth articles.
   **Details**: For each event, provide a brief overview, including the exact date it will occur.
Stock Recommendations Linked to Events:
  **Action**: For each main event, suggest 2-3 stocks (with tickers) that may experience price movement due to the event. The focus here is on short-term gains within the week.
Analysis:
  **Reasoning**: Provide a concise explanation for each stock choice, linking it to the specific event. Explain why you believe the event could impact the stock price. Include exact date when you think share should be bought or price at which it should be bought and date at which it should be sold or price a which it should be sold.
  **Confidence Level**: Assign a confidence level from 1 to 5 for each stock recommendation, based on your analysis and the potential impact of the event.
Remember, the goal is to provide actionable insights while emphasizing the speculative nature of these recommendations. 

Report will be shared with several people so:
* do not print any my personal information in the report
* in the end
   * print: "Generated by Jess, AI created by Viacheslav Kovalevskyi"
   * print: "For any questions: viacheslav@kovalevskyi.com"
"""