prompt = """I want to you create overivew of the financial market for the week. Specifically:
* TLDR of the main events of the upcoming week - in order to do so check events, and do some google search about them and read any articles you need to read to give me TLDR. Each event should include exact date it will occure.
* for each main event, suggest 2-3 shares (with tickers) that you think might go up in price DUE to the event. Idea to buy them and sell in a week (so the assumption that it will go up this week, not just long term). Suggest specific shares with tickers. For each provide short TLDR why you pick each, with the pointer that specific event this week that you think will impact the price and why you think that way. For each pick also give a level of confidence in your oppinion (from 1 to 5).

Rerport should be not too long, maybe 2-pager max. This is for high risk/high reward investments so it is ok not to be sure, just suggest to the best of your abilities. Act as a professional financial trader, not as a gambler or not as a friend.

Report will be shared with several people so:
* do not print any my personal information in the report
* in the end
   * print: "Generated by Jess, AI created by Viacheslav Kovalevskyi"
   * print: "For any questions: viacheslav@kovalevskyi.com"

Keep in mind that final message will be sent via the telegram, so use Markdown formatting accordingly.
"""

class MarketOverviewRutine(object):

    def __init__(self, jess, schedule) -> None:
        self.jess = jess
        schedule.every().sunday.at("06:00").do(self.send_market_overview)

    def send_market_overview(self):
        self.jess.send_message(prompt)